version: '3'
services:
  api:
    build:
      context: ./django-api
    ports:
      - "8000:8000"
    volumes:
      - ./django-api/:/api
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    build:
      context: ./mysql
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf