from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from .views import (
    CreateAccountView,
    LogoutView,
    TaskDetailAPIView, 
    TaskCreateAPIView,
    TaskUpdateAPIView,
    TaskToggleFocusAPIView,
    TaskToggleDoneAPIView,
    TaskListFocusedAPIView,
    TaskListDoneAPIView,
    TaskListReadinessInboxAPIView,
    TaskListReadinessSometimeAPIView,
    TaskListReadinessAnytimeAPIView,
    TaskListReadinessWaitingAPIView,
    TaskDisableAPIView,
    TaskListAPIView,
    SimpleTagCreateAPIView,
    SimpleTagUpdateAPIView,
    SimpleTagDisableAPIView,
    SimpleTagListAPIView,
    SimpleTagDetailAPIView,
    PersonCreateAPIView,
    PersonUpdateAPIView,
    PersonDisableAPIView,
    PersonListAPIView,
    PersonDetailAPIView,
    PlaceCreateAPIView,
    PlaceUpdateAPIView,
    PlaceDisableAPIView,
    PlaceListAPIView,
    PlaceDetailAPIView,
    AreaCreateAPIView,
    AreaUpdateAPIView,
    AreaDisableAPIView,
    AreaListAPIView,
    AreaDetailAPIView,
)

urlpatterns = [
    path('account/create/', CreateAccountView.as_view(), name='account_create'),
    path('auth/', obtain_auth_token, name='obtain-token'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('task/<int:pk>/', TaskDetailAPIView.as_view(), name='task_detail'),
    path('task/create/', TaskCreateAPIView.as_view(), name='task_create'),
    path('task/update/<int:pk>/', TaskUpdateAPIView.as_view(), name='task_update'),
    path('task/toggle-focus/<int:pk>/', TaskToggleFocusAPIView.as_view(), name='task_toggle_focus'),
    path('task/toggle-done/<int:pk>/', TaskToggleDoneAPIView.as_view(), name='task_toggle_done'),
    path('task/focused/', TaskListFocusedAPIView.as_view(), name='focused_task_list'),
    path('task/done/', TaskListDoneAPIView.as_view(), name='done_task_list'),
    path('task/inbox/', TaskListReadinessInboxAPIView.as_view(), name='inbox_task_list'),
    path('task/sometime/', TaskListReadinessSometimeAPIView.as_view(), name='sometime_task_list'),
    path('task/anytime/', TaskListReadinessAnytimeAPIView.as_view(), name='anytime_task_list'),
    path('task/waiting/', TaskListReadinessWaitingAPIView.as_view(), name='waiting_task_list'),
    path('task/disable/<int:pk>/', TaskDisableAPIView.as_view(), name='task_disable'),
    path('task/', TaskListAPIView.as_view(), name='task_list'),
    path('simpletag/create/', SimpleTagCreateAPIView.as_view(), name='simpletag_create'),
    path('simpletag/update/<int:pk>/', SimpleTagUpdateAPIView.as_view(), name='simpletag_update'),
    path('simpletag/disable/<int:pk>/', SimpleTagDisableAPIView.as_view(), name='simpletag_disable'),
    path('simpletag/', SimpleTagListAPIView.as_view(), name='simpletag_list'),
    path('simpletag/<int:pk>/', SimpleTagDetailAPIView.as_view(), name='simpletag_detail'),
    path('person/create/', PersonCreateAPIView.as_view(), name='person_create'),
    path('person/update/<int:pk>/', PersonUpdateAPIView.as_view(), name='person_update'),
    path('person/disable/<int:pk>/', PersonDisableAPIView.as_view(), name='person_disable'),
    path('person/', PersonListAPIView.as_view(), name='person_list'),
    path('person/<int:pk>/', PersonDetailAPIView.as_view(), name='person_detail'),
    path('place/create/', PlaceCreateAPIView.as_view(), name='place_create'),
    path('place/update/<int:pk>/', PlaceUpdateAPIView.as_view(), name='place_update'),
    path('place/disable/<int:pk>/', PlaceDisableAPIView.as_view(), name='place_disable'),
    path('place/', PlaceListAPIView.as_view(), name='place_list'),
    path('place/<int:pk>/', PlaceDetailAPIView.as_view(), name='place_detail'),
    path('area/create/', AreaCreateAPIView.as_view(), name='area_create'),
    path('area/update/<int:pk>/', AreaUpdateAPIView.as_view(), name='area_update'),
    path('area/disable/<int:pk>/', AreaDisableAPIView.as_view(), name='area_disable'),
    path('area/', AreaListAPIView.as_view(), name='area_list'),
    path('area/<int:pk>/', AreaDetailAPIView.as_view(), name='area_detail'),
]