# Generated by Django 3.2.16 on 2023-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='set_focus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
