# Generated by Django 3.2.16 on 2023-01-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='readiness',
            field=models.CharField(choices=[('inbox', 'inbox'), ('anytime', 'Anytime'), ('waiting', 'Waiting'), ('sometime', 'Sometime')], default='inbox', max_length=20),
        ),
    ]
